---
global:
  nameOverride: &app_name scroll-proving-sindri
  fullnameOverride: *app_name
image:
  repository: ghcr.io/sindri-labs/sindri-scroll-sdk/prover
  pullPolicy: Always
  tag: ""
command:
  - "/bin/sh"
  - "-c"
  - "exec sindri-scroll-sdk --config /sdk_prover/config.json"
resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "1000m"
persistence:
  config:
    enabled: true
    type: configMap
    mountPath: /sdk_prover/
    name: scroll-proving-sindri-config
  keys:
    enabled: true
    type: pvc
    mountPath: /keys/
    size: 10Mi
    accessMode: ReadWriteOnce
service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 80
probes:
  liveness:
    !!merge <<: *default_probes
  readiness:
    !!merge <<: *default_probes
  startup:
    !!merge <<: *default_probes
# scrollConfig should be overwritten the config in json format. See the example below.
scrollConfig: |
  {}

# {
#     "sdk_config": {
#         "prover_name_prefix": "sindri_",
#         "keys_dir": "keys",
#         "db_path": "db",
#         "coordinator": {
#             "base_url": "https://coordinator-api:80",
#             "retry_count": 3,
#             "retry_wait_time_sec": 5,
#             "connection_timeout_sec": 60
#         },
#         "l2geth": {
#             "endpoint": "https://l2-rpc:8545"
#         },
#         "prover": {
#             "circuit_types": [1,2,3],
#             "circuit_version": "v0.13.1",
#             "n_workers": 1
#         },
#         "health_listener_addr": "0.0.0.0:5678"
#     },
#     "base_url": "https://sindri.app",
#     "api_key": "<your Sindri API key>",
#     "retry_count": 3,
#     "retry_wait_time_sec": 5,
#     "connection_timeout_sec": 60
# }


