---
global:
  nameOverride: &app_name scroll-proving-sindri
  fullnameOverride: *app_name
image:
  repository: ghcr.io/sindri-labs/sindri-scroll-sdk/prover
  pullPolicy: Always
  tag: ""
command:
  - "/bin/sh"
  - "-c"
  - "exec sindri-scroll-sdk --config /sdk_prover/config.json"
resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "1000m"
persistence:
  config:
    enabled: true
    type: configMap
    mountPath: /sdk_prover/
    name: scroll-proving-sindri-config
  keys:
    enabled: true
    type: pvc
    mountPath: /keys/
    size: 10Mi
    accessMode: ReadWriteOnce
service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 80
probes:
  liveness:
    !!merge <<: *default_probes
  readiness:
    !!merge <<: *default_probes
  startup:
    !!merge <<: *default_probes
# scrollConfig should be overwritten the config in json format. See the example below.
scrollConfig: |
  {}

# {
#   "prover_name_prefix": "sindri_",
#   "keys_dir": "keys",
#   "coordinator": {
#     "base_url": "https://coordinator-api.scrollsdk",
#     "retry_count": 3,
#     "retry_wait_time_sec": 5,
#     "connection_timeout_sec": 60
#   },
#   "l2geth": {
#     "endpoint": "https://l2-rpc.scrollsdk"
#   },
#   "prover": {
#     "circuit_types": [1,2,3],
#     "circuit_version": "v0.13.1",
#     "cloud": {
#       "base_url": "https://sindri.app/api/v1/",
#       "api_key": "<API_KEY>",
#       "retry_count": 3,
#       "retry_wait_time_sec": 5,
#       "connection_timeout_sec": 60
#     }
#   },
#   "db_path": "db"
# }
